"""CommerceProvider: the backend-agnostic interface every commerce data
source (native Firestore, Shopify, future platforms) implements.

`tenant_id` is the required first argument on every method — there is no
method signature that can be called without one. This is the concrete,
enforced (and tested — see tests/unit/test_cross_tenant_isolation.py)
guarantee behind "no implicit tenant" (Global Constraints, this plan).
"""

from typing import Optional, Protocol

from customer_support_mas.providers.models import Invoice, Order, Payment, Product, RefundResult


class CommerceProvider(Protocol):
    def get_order(self, tenant_id: str, order_id: str) -> Optional[Order]: ...

    def list_orders_for_customer(self, tenant_id: str, customer_id: str) -> list[Order]: ...

    def get_product(self, tenant_id: str, product_id: str) -> Optional[Product]: ...

    def get_inventory(self, tenant_id: str, product_id: str) -> Optional[int]: ...

    def get_invoice(self, tenant_id: str, invoice_id: str) -> Optional[Invoice]: ...

    def get_invoice_by_order(self, tenant_id: str, order_id: str) -> Optional[Invoice]: ...

    def list_invoices_for_customer(self, tenant_id: str, customer_id: str) -> list[Invoice]: ...

    def get_payment(self, tenant_id: str, order_id: str) -> Optional[Payment]: ...

    def list_payments_for_customer(self, tenant_id: str, customer_id: str) -> list[Payment]: ...

    def list_refunds_for_order(self, tenant_id: str, order_id: str) -> list[dict]: ...

    def search_products(self, tenant_id: str, query: str, limit: int = 5) -> list[Product]: ...

    def verify_order_ownership(self, tenant_id: str, order_id: str, customer_id: str) -> tuple[bool, Optional[Order], str]: ...

    def verify_invoice_ownership(self, tenant_id: str, invoice_id: str, customer_id: str) -> tuple[bool, Optional[Invoice], str]: ...

    def execute_refund(
        self, tenant_id: str, order_id: str, customer_id: str, items: list[dict], amount: float
    ) -> RefundResult: ...
